import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import cn from "classnames";
import Link from "next/link";

export default function Home() {
  const [name1, setName1] = useState(null);
  const [name2, setName2] = useState(null);
  const [stepTwo, setStepTwo] = useState(false);
  const [stepThree, setStepThree] = useState(false);

  const handleProceed = () => {
    if (!stepTwo) {
      setStepTwo(true);
      return;
    }
    localStorage.setItem("users", JSON.stringify({ users: [name1, name2] }));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={cn(styles.main, { [styles.steptwo]: stepTwo })}>
        {stepTwo && name2 && (
          <div
            className={cn(styles.proceedButton, { [styles.vis]: stepThree })}
          >
            <Link href="/disclaimer" passHref>
              <a onClick={handleProceed}>Start game!</a>
            </Link>
          </div>
        )}
        <div className={cn(styles.firstSection)}>
          <input
            value={name1}
            placeholder="Enter Name..."
            onFocus={() => setStepTwo(false)}
            onBlur={() => setStepTwo(true)}
            onChange={(e) => setName1(e.target.value)}
            className={styles.input}
          />
          <div
            className={cn(styles.divider, { [styles.shown]: stepTwo })}
          ></div>
        </div>
        <div className={styles.secondSection}>
          <input
            value={name2}
            placeholder="Name..."
            onChange={(e) => setName2(e.target.value)}
            className={styles.input}
            onFocus={() => setStepThree(false)}
            onBlur={() => setStepThree(true)}
          />
          <div className={styles.divider}></div>
        </div>
      </main>
    </div>
  );
}
